# Cross-compilation linker configuration.
# Linux linkers are provided by the following Debian/Ubuntu packages:
#   aarch64-linux-gnu-gcc → gcc-aarch64-linux-gnu
#   i686-linux-gnu-gcc    → gcc-i686-linux-gnu

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.i686-unknown-linux-gnu]
linker = "i686-linux-gnu-gcc"
